// ---------------------------------------------------------------------------------------
//                                 SpawnDev.ILGPU.WebGPU
//                        Copyright (c) 2024 SpawnDev Project
//
// File: WebGPUBackend.cs
//
// WebGPU/WGSL backend for ILGPU using CodeGeneratorBackend pattern.
// ---------------------------------------------------------------------------------------

using global::ILGPU;
using global::ILGPU.Backends;
using global::ILGPU.Backends.EntryPoints;
using global::ILGPU.IR;
using global::ILGPU.IR.Analyses;
using global::ILGPU.IR.Transformations;
using global::ILGPU.Runtime;
using System.Text;

namespace SpawnDev.ILGPU.WebGPU.Backend
{
    /// <summary>
    /// WebGPU/WGSL backend for ILGPU.
    /// Compiles ILGPU IR to WGSL shader code using the CodeGeneratorBackend pattern.
    /// </summary>
    public class WebGPUBackend : CodeGeneratorBackend<
        WGSLIntrinsic.Handler,
        WGSLCodeGenerator.GeneratorArgs,
        WGSLCodeGenerator,
        StringBuilder>
    {
        #region Instance

        /// <summary>
        /// Creates a new WebGPU backend.
        /// </summary>
        /// <param name="context">The ILGPU context.</param>
        public WebGPUBackend(Context context)
            : base(
                  context,
                  new WebGPUCapabilityContext(),
                  BackendType.WebGPU,
                  new WebGPUArgumentMapper(context))
        {
            InitIntrinsicProvider();
            InitializeKernelTransformers(builder =>
            {
                // Add any WebGPU-specific transformers
                var transformerBuilder = Transformer.CreateBuilder(
                    TransformerConfiguration.Empty);
                builder.Add(transformerBuilder.ToTransformer());
            });
        }

        #endregion

        #region Properties

        /// <summary>
        /// Returns the associated argument mapper.
        /// </summary>
        public new WebGPUArgumentMapper ArgumentMapper =>
            base.ArgumentMapper as WebGPUArgumentMapper;

        #endregion

        #region Methods

        /// <summary>
        /// Creates a new entry point.
        /// </summary>
        protected override EntryPoint CreateEntryPoint(
            in EntryPointDescription entry,
            in BackendContext backendContext,
            in KernelSpecialization specialization) =>
            new EntryPoint(
                entry,
                backendContext.SharedMemorySpecification,
                specialization);

        /// <summary>
        /// Creates the main kernel builder and initializes generator args.
        /// </summary>
        protected override StringBuilder CreateKernelBuilder(
            EntryPoint entryPoint,
            in BackendContext backendContext,
            in KernelSpecialization specialization,
            out WGSLCodeGenerator.GeneratorArgs data)
        {
            var builder = new StringBuilder();

            builder.AppendLine("//");
            builder.Append("// Generated by SpawnDev.ILGPU.WebGPU v");
            builder.AppendLine(Context.Version);
            builder.AppendLine("//");
            builder.AppendLine();

            var typeGenerator = new WGSLTypeGenerator(Context.TypeContext);

            data = new WGSLCodeGenerator.GeneratorArgs(
                this,
                typeGenerator,
                entryPoint,
                backendContext.SharedAllocations,
                backendContext.DynamicSharedAllocations);

            return builder;
        }

        /// <summary>
        /// Creates a function-code generator for helper methods.
        /// </summary>
        protected override WGSLCodeGenerator CreateFunctionCodeGenerator(
            Method method,
            Allocas allocas,
            WGSLCodeGenerator.GeneratorArgs data) =>
            new WGSLFunctionGenerator(data, method, allocas);

        /// <summary>
        /// Creates a kernel-code generator for the main entry point.
        /// </summary>
        protected override WGSLCodeGenerator CreateKernelCodeGenerator(
            in AllocaKindInformation sharedAllocations,
            Method method,
            Allocas allocas,
            WGSLCodeGenerator.GeneratorArgs data) =>
            new WGSLKernelFunctionGenerator(data, method, allocas);

        /// <summary>
        /// Creates the final compiled kernel.
        /// </summary>
        protected override CompiledKernel CreateKernel(
            EntryPoint entryPoint,
            CompiledKernel.KernelInfo? kernelInfo,
            StringBuilder builder,
            WGSLCodeGenerator.GeneratorArgs data)
        {
            var wgslSource = builder.ToString();
            return new WebGPUCompiledKernel(Context, entryPoint, wgslSource);
        }

        #endregion
    }

    /// <summary>
    /// Represents a compiled WebGPU/WGSL kernel.
    /// </summary>
    public class WebGPUCompiledKernel : CompiledKernel
    {
        /// <summary>
        /// Gets the generated WGSL source code.
        /// </summary>
        public string WGSLSource { get; }

        /// <summary>
        /// Creates a new compiled WebGPU kernel.
        /// </summary>
        public WebGPUCompiledKernel(Context context, EntryPoint entryPoint, string wgslSource)
            : base(context, entryPoint, null)
        {
            WGSLSource = wgslSource;
        }
    }

    /// <summary>
    /// Argument mapper for WebGPU kernel parameters.
    /// </summary>
    public class WebGPUArgumentMapper : ArgumentMapper
    {
        /// <summary>
        /// Creates a new WebGPU argument mapper.
        /// </summary>
        public WebGPUArgumentMapper(Context context) : base(context) { }

        /// <summary>
        /// Maps a view type to its WebGPU equivalent.
        /// </summary>
        protected override System.Type MapViewType(System.Type viewType, System.Type elementType)
        {
            return viewType;
        }

        /// <summary>
        /// Maps a view instance for kernel invocation.
        /// </summary>
        protected override void MapViewInstance<TILEmitter, TSource, TTarget>(
            in TILEmitter emitter,
            System.Type viewType,
            in TSource source,
            in TTarget target)
        {
            // View mapping is handled separately for WebGPU
        }
    }

    /// <summary>
    /// Capability context for WebGPU backend.
    /// </summary>
    public class WebGPUCapabilityContext : CapabilityContext
    {
        /// <summary>
        /// Creates a new WebGPU capability context.
        /// </summary>
        public WebGPUCapabilityContext() : base()
        {
        }
    }
}
